### ISSUE TITLE
Add description and goals of App

### ISSUE THREAD

**Issue by francopestilli** [brainlife/app-documentation-template#1]
hi, @DanNBullock can you please add a description of what this App is meant to do right under the title of the app, please?
one or two lines.

Something like:

"This App will process OCT Data outputted from the MAYA system. Note that the data needs to be preprocessed to be compatible with the App. Below we provide instructions about how to preprocess the data and make it compatible with the App."

**Comment by DanNBullock** [comment]
Change made here:  https://github.com/DanNBullock/app-voxeleronOCT/commit/dc46a734d6b6e3daf1cfc5fda0e211c9f63ca5db#diff-0730bb7c2e8f9ea2438b52e419dd86c9

Also, did you mean to make this comment on the [voxeleron app issue page](https://github.com/DanNBullock/app-voxeleronOCT/issues)?  I think that may lead to a clearer workflow, but I'm not sure.

**Comment by francopestilli** [comment]
thanks for making the changes, @DanNBullock can you push the changes to this repo also, please?

**Comment by francopestilli** [comment]
PS I do not have r/w access on your repo, cannot pull into this one. @DanNBullock done actually

**Comment by DanNBullock** [comment]
> thanks for making the changes, @DanNBullock can you push the changes to this repo also, please?

By "this repo", do you mean "https://github.com/brainlife/app-documentation-template" ?  I'm not sure how I would push the voxeleron-app code to this?  I think these are completely different sets of code.  Is there somewhere else you wanted it pushed?

> PS I do not have r/w access on your repo, cannot pull into this one. @DanNBullock done actually

Does this mean that you were able to make the change you wanted?  Also, insofar as I can tell you are a contributor, do you need a different access setting to make changes?
